@startuml

title Diagramme de classe du package modele

package modele {

    class Player {
        - int currentBoatIndex
        - List<Bateau> boatList
        - List<Point2D> tirsEchoues
        - Strategie[] strategies
        - int currentStrategie
        - Strategie strategie
        + shoot(Point2D pos)
        + boolean receiveShoot(Point2D pos,int damage)
        + boolean chooseBoat(pos : Point2D)
        + int getBoatIndexFromPos(pos : Point2D)
        + Bateau getCurrentBoat()
        + Point2D addFailedShoot(pos)
        + Strategie getStrategie()
        + Strategie setStrategie(strategie)
    }
    Player --"*" boatFactory.Bateau
    Player -- "*" Point2D : "Tirs échoués"
    Player -- "0..1" Strategie
    Player ..> Serializable

    class BatailleNavale {
        - width : int
        - height : int
        - turnPlayer : boolean
        - epoque : int
        - Player humain
        - Player ia

        - List<Bateau> initListBateau()
        + playerShoot(pos : Point2D)
        + boolean checkBoatsPosition()

    }
    
    Interface Strategie {
        + generateShoot() : Point2D
    }
    
    class StrategieAlea{
        - lastShootHasTouched : boolean
        + generateShoot() : Point2D
    }
    
    class StrategieCroix{
        - lastShootHasTouched : boolean
        + generateShoot() : Point2D
    }

    class Point2D{
    }
    
    
    strategieAlea ..> Strategie
    strategieCroix ..> Strategie
    BatailleNavale --"1" Player : "Humain"
    BatailleNavale --"1" Player : "IA"
    BatailleNavale ..> Serializable
}


@enduml