@startuml
' Split into 2 pages
page 2x1
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black
title Diagramme de classe du package game

package game {
    
    enum Cmd {
        ARROW_LEFT,
        ARROW_RIGHT,
        ARROW_UP,
        ARROW_DOWN,
        ENTER
    }
    
    enum GameState {
        MENU
        RUNNING,
        EPOCH_CHOOSE,
        RESUME_GAME,
        FINISHED
    }

    class Game {
        - gameState : GameState
        - String currentEpoch
        - boolean fileChooserIsOpen
        - boolean isSaved
        - BatailleNavale batailleNavale

        + evolve(cmd : Cmd, click Point2D)
        + restart()
        + launchBatailleNavale(String epoque)
        - save()
        - checkFinishedGame()
        - evolveRunning(cmd : Cmd, click Point2D)
        - evolveRunningNotReady(cmd : Cmd)
        - evolveRunningReady(cmd : Cmd)
        - evolveMenu(cmd : Cmd, click Point2D)
        - evolveEpochChoose(cmd : Cmd, click Point2D)
        - evolveResumeGame(cmd : Cmd, click Point2D)

    }

    Game -down-"1" modele.BatailleNavale

    Game .down.> engine.Game

    class Painter {
        - drawMenu()
        - drawEpochChoose()
        - drawRunning()
        - drawResumeGame()
    }
    Painter .down.> engine.GamePainter
    Painter -down- "1" modele.BatailleNavale

    class Controller {
        - commandeEnCours : Cmd
        - clickEnCours : Point2D
        + keyPressed(e : KeyEvent) 
        + mouseClicked(e : MouseEvent)
    }
    Controller .down.> engine.GameController

    class ImageFactory << (S,#FF7700) Singleton >>{
        - {static} ImageFactory instance

        - BufferedImage background
        - BufferedImage sea

        - BufferedImage boutBateauXVIII
        - BufferedImage milieuBateauXVIII

        - BufferedImage boutBreakBateauXVIII
        - BufferedImage milieuBreakBateauXVIII

        - BufferedImage boutBateauXIX
        - BufferedImage milieuBateauXIX

        - BufferedImage boutBreakBateauXIX
        - BufferedImage milieuBreakBateauXIX

        - BufferedImage explosion
        - BufferedImage fail

        + {static} ImageFactory getInstance()
        - loadImages()
    }

    package menu{
        class EpochChoose{
            - Game game
            + void handleEnter();
        }
        class FinishedGame{
            - Game game
            + void handleEnter();
        }
        class MainMenu{
                    - Game game
                    + void handleEnter();
        }
        class ResumeGame{
                    - Game game
                    + void handleEnter();
        }
        abstract class Menu{
            # String[] menuEntries
            # int selectedIndex
            # String title

            + void elvolve(Cmd cmd)
            + void paint(Graphics2D crayon)
            # {abstract} void handleEnter()
            + setTitle(String title)
        }

        EpochChoose --> Menu
        FinishedGame --> Menu
        MainMenu --> Menu
        ResumeGame --> Menu

    }
        Game -down-"4" Menu

}


package engine {
    interface GameController
    interface GamePainter
    interface Game
}

package modele {
    class BatailleNavale
}

@enduml