@startuml

title Diagramme d'états de la bataille navale

[*] --> Menu_principal
MENU --> EPOCH_CHOOSE : "Nouvelle partie"
MENU --> RESUME_GAME : "Reprendre une partie"
MENU --> [*] : "Quitter"

EPOCH_CHOOSE --> RUNNING : "Choix de l'époque"
EPOCH_CHOOSE --> MENU : "Retourner au menu"

RESUME_GAME --> RUNNING : "Choisir un fichier"
RESUME_GAME --> MENU : "Retourner au menu"

RUNNING --> MENU : "Sauvegarder et quitter"
RUNNING --> MENU : "Quitter sans sauvegarder"

@enduml