@startuml

title Le joueur sélectionne un bateau et tir 

activate humain
activate game
activate humain
activate ia
activate game.batailleNavale

opt Clique en (x, y) dans la grille de gauche (pos : Point2D dans l'application)
    game -> game.batailleNavale : this.batailleNavale.getHumain()
    game.batailleNavale --> game : humain
    game -> humain : humain.chooseBoat(pos)
    loop bateau in humain.boatList
        humain -> bateau : detectBoat(pos)
        bateau --> humain : touche
        opt touche
            humain -> humain : currentBoatIndex = index
        end
    end
end

opt Un bateau a été sélectionné et il y a un clique en (x, y) dans la grille de droite (pos: Point2D dans l'application)
    game -> game.batailleNavale : this.batailleNavale.playerShoot(pos)
    
    game.batailleNavale -> humain : player.getCurrentBoat()
    humain --> game.batailleNavale : boat
    game.batailleNavale -> boat : boat.getDegat()
    boat --> game.batailleNavale : degat
    
    game.batailleNavale -> ia : ia.receiveShoot(pos, damage)
    loop bateau in ia.boatList
        ia -> bateau : detectBoat(pos)
        bateau --> ia : touche
        opt touche
            bateau -> bateau : bateau.setHP(bateau.getHP() - degat)
        end
    end
 
    ia --> game.batailleNavale : touche

    opt not touche
        game.batailleNavale -> humain : humain.addFailedShoot(pos)
    end
    

end



@enduml