@startuml

package modele {

    class Player {
        - currentBoatIndex : int
        + shoot(pos : Point2D)
        + findBoatAtPos(pos : Point2D) : Boat
    }
    Player --"*" boatFactory.Boat
    Player -- "*" Point2D : "Tires échoués"

    class BatailleNavale {
        - width : int
        - height : int
        - turn : boolean
        - epoch : int
        + shoot(pos : Point2D)
    }
    BatailleNavale --"1" Player : "Humain"
    BatailleNavale --"1" Player : "IA"
}


@enduml